[package]
name = "foxsay"
version = "0.1.0"
edition = "2021"
authors = ["ArcticSpaceFox <contact@spacefoxlabs.com>"]

[dependencies]
atty = "0.2"
colored = "2.0"
exitfailure = "0.5"
failure = "0.1"
structopt = "0.3"